### ISSUE TITLE
Gallery image loading issue

### ISSUE THREAD

**Issue by rssilva01** [fahidattique55/FAImageCropper#10]
Hey, has anyone else had the issue where some of the images from the phone's gallery don't load? I've attached a screenshot showing the issue. Only some users' devices are having the problem. It does not seem to be related to photo gallery permission because some of the photos are able to load. Any help here would be great - thanks!
![gallery issue 2](https://user-images.githubusercontent.com/34591807/34067300-d7bb3ef0-e1ef-11e7-9641-3d3711ad5b8c.jpeg)

**Comment by fahidattique55** [comment]
Hey @rssilva01 

Can you share some images that are not loading while using the library and you are able to see them in iPhone's native Photos application? It will help me to diagnose the issue.

Thanks

**Comment by rssilva01** [comment]
Hey fahidattique55,

We figured out the reason - it was due to iCloud photos not storing the full image on device. We had to specify to download images from iCloud and now it works fine. Thanks for the response though!

**Comment by fahidattique55** [comment]
@rssilva01

Thanks for informing :)
