### ISSUE TITLE
when i scroll faster to app memory increase 

### ISSUE THREAD

**Issue by ominfowaveIOS** [fahidattique55/FAImageCropper#3]
hello fahidattique,
when i run this app memory consumption is 32mb but when  i scroll down faster it reaches around 400mb and  app get crash.

**Comment by fahidattique55** [comment]
Hello ominfowaveIOS,

Thanks for reporting this bug. I have fixed it by adding placeholder image size of **"100 x 100"** while loading images from Gallery. Please let me know if you face any further issues.

Thanks & Regards
