### ISSUE TITLE
 get image and video both

### ISSUE THREAD

**Issue by ominfowaveIOS** [fahidattique55/FAImageCropper#4]
hello Fahid Attique . 
 this library possible to get image and video both  ??

**Comment by fahidattique55** [comment]
Hello @ominfowaveIOS,

Current version of FAImageCropper does not include the support for videos. But yes, its an innovative idea to integrate in it. Can you please put some requirements about how should it works and what things we should added in it to make it more interactive ? Do you have any suggestions ? If you have then please share it with me at fahidattique55@gmail.com. 

Thank you
